# Generated by Django 5.0 on 2023-12-09 17:53

import customers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField()),
                ('total_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_wsp', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('items', models.JSONField(default=customers.models.default_stock_items, help_text='Refer to documentation & jsonformatter.org.')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('region', models.CharField(blank=True, help_text='Enter comma-separated values with underscore (e.g., Western, South_Indian, North_Indian)', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('cart', models.JSONField(blank=True, default=list, help_text='Refer to jsonformatter.org', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customer_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customer_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
